version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
  app:
    container_name: app
    depends_on:
      - mongo
    build: ./
    restart: unless-stopped
    # ports:
    #   - 3000:3000
    stdin_open: true
    tty: true
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db:
  caddy_data:
  caddy_config:
