version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:5
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  app:
    container_name: app
    depends_on:
      - mongo
    build: ./
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mongo
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
      - MONGODB_URL = mongodb://myuser:mypassword@mydb:27017/
    stdin_open: true
    tty: true

volumes:
  db:
